version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.sun.xml.bind:jaxb-impl"
    groups:
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"
      jackson:
        patterns:
          - "jackson"
          - "*jackson"
          - "jackson*"
  
