//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.31 at 11:54:38 AM CET 
//


package org.jesperancinha.plugins.omni.reporter.domain.jacoco;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="missed" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="covered" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "counter")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
public class Counter {

    @XmlValue
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String value;
    @XmlAttribute(name = "type")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String type;
    @XmlAttribute(name = "missed")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String missed;
    @XmlAttribute(name = "covered")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String covered;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the missed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getMissed() {
        return missed;
    }

    /**
     * Sets the value of the missed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setMissed(String value) {
        this.missed = value;
    }

    /**
     * Gets the value of the covered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getCovered() {
        return covered;
    }

    /**
     * Sets the value of the covered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setCovered(String value) {
        this.covered = value;
    }

}
