//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.01 at 10:36:31 PM CET 
//


package org.jesperancinha.plugins.omni.reporter.domain.jacoco;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="nr" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="mi" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="ci" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="mb" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="cb" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "line")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
public class Line {

    @XmlValue
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    protected String value;
    @XmlAttribute(name = "nr")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    protected Integer nr;
    @XmlAttribute(name = "mi")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    protected Integer mi;
    @XmlAttribute(name = "ci")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    protected Integer ci;
    @XmlAttribute(name = "mb")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    protected Integer mb;
    @XmlAttribute(name = "cb")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    protected Integer cb;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the nr property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public Integer getNr() {
        return nr;
    }

    /**
     * Sets the value of the nr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public void setNr(Integer value) {
        this.nr = value;
    }

    /**
     * Gets the value of the mi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public Integer getMi() {
        return mi;
    }

    /**
     * Sets the value of the mi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public void setMi(Integer value) {
        this.mi = value;
    }

    /**
     * Gets the value of the ci property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public Integer getCi() {
        return ci;
    }

    /**
     * Sets the value of the ci property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public void setCi(Integer value) {
        this.ci = value;
    }

    /**
     * Gets the value of the mb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public Integer getMb() {
        return mb;
    }

    /**
     * Sets the value of the mb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public void setMb(Integer value) {
        this.mb = value;
    }

    /**
     * Gets the value of the cb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public Integer getCb() {
        return cb;
    }

    /**
     * Sets the value of the cb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public void setCb(Integer value) {
        this.cb = value;
    }

}
