//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.31 at 11:54:38 AM CET 
//


package org.jesperancinha.plugins.omni.reporter.domain.jacoco;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}counter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "counters"
})
@XmlRootElement(name = "method")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
public class Method {

    @XmlElement(name = "counter")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected List<Counter> counters;
    @XmlAttribute(name = "name")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String name;
    @XmlAttribute(name = "desc")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String desc;
    @XmlAttribute(name = "line")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String line;

    /**
     * Gets the value of the counters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the counters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCounters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Counter }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public List<Counter> getCounters() {
        if (counters == null) {
            counters = new ArrayList<Counter>();
        }
        return this.counters;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setLine(String value) {
        this.line = value;
    }

}
