//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.31 at 11:54:38 AM CET 
//


package org.jesperancinha.plugins.omni.reporter.domain.jacoco;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="dump" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "sessioninfo")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
public class Sessioninfo {

    @XmlValue
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String value;
    @XmlAttribute(name = "id")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String id;
    @XmlAttribute(name = "start")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String start;
    @XmlAttribute(name = "dump")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    protected String dump;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setStart(String value) {
        this.start = value;
    }

    /**
     * Gets the value of the dump property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public String getDump() {
        return dump;
    }

    /**
     * Sets the value of the dump property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-12-31T11:54:38+01:00", comments = "JAXB RI v2.3.2")
    public void setDump(String value) {
        this.dump = value;
    }

}
