//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.01 at 10:36:31 PM CET 
//


package org.jesperancinha.plugins.omni.reporter.domain.jacoco;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}line" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}counter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lines",
    "counters"
})
@XmlRootElement(name = "sourcefile")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
public class Sourcefile {

    @XmlElement(name = "line")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    protected List<Line> lines;
    @XmlElement(name = "counter")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    protected List<Counter> counters;
    @XmlAttribute(name = "name")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    protected String name;

    /**
     * Gets the value of the lines property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lines property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLines().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Line }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public List<Line> getLines() {
        if (lines == null) {
            lines = new ArrayList<Line>();
        }
        return this.lines;
    }

    /**
     * Gets the value of the counters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the counters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCounters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Counter }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public List<Counter> getCounters() {
        if (counters == null) {
            counters = new ArrayList<Counter>();
        }
        return this.counters;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2022-01-01T10:36:31+01:00", comments = "JAXB RI v2.3.2")
    public void setName(String value) {
        this.name = value;
    }

}
