//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.30 at 08:16:47 AM CET 
//


package org.jesperancinha.plugins.omni.reporter.domain.saga;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for coverageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coverageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sources" type="{}sourcesType"/&gt;
 *         &lt;element name="packages" type="{}packagesType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="branch-rate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="branches-covered" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="branches-valid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="complexity" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="line-rate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="lines-valid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="lines-covered" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coverageType", propOrder = {
    "sources",
    "packages"
})
public class CoverageType {

    @XmlElement(required = true)
    protected SourcesType sources;
    @XmlElement(required = true)
    protected PackagesType packages;
    @XmlAttribute(name = "branch-rate")
    protected String branchRate;
    @XmlAttribute(name = "branches-covered")
    protected String branchesCovered;
    @XmlAttribute(name = "branches-valid")
    protected String branchesValid;
    @XmlAttribute(name = "complexity")
    protected String complexity;
    @XmlAttribute(name = "line-rate")
    protected String lineRate;
    @XmlAttribute(name = "lines-valid")
    protected String linesValid;
    @XmlAttribute(name = "lines-covered")
    protected String linesCovered;
    @XmlAttribute(name = "timestamp")
    protected String timestamp;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link SourcesType }
     *     
     */
    public SourcesType getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourcesType }
     *     
     */
    public void setSources(SourcesType value) {
        this.sources = value;
    }

    /**
     * Gets the value of the packages property.
     * 
     * @return
     *     possible object is
     *     {@link PackagesType }
     *     
     */
    public PackagesType getPackages() {
        return packages;
    }

    /**
     * Sets the value of the packages property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackagesType }
     *     
     */
    public void setPackages(PackagesType value) {
        this.packages = value;
    }

    /**
     * Gets the value of the branchRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchRate() {
        return branchRate;
    }

    /**
     * Sets the value of the branchRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchRate(String value) {
        this.branchRate = value;
    }

    /**
     * Gets the value of the branchesCovered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchesCovered() {
        return branchesCovered;
    }

    /**
     * Sets the value of the branchesCovered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchesCovered(String value) {
        this.branchesCovered = value;
    }

    /**
     * Gets the value of the branchesValid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchesValid() {
        return branchesValid;
    }

    /**
     * Sets the value of the branchesValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchesValid(String value) {
        this.branchesValid = value;
    }

    /**
     * Gets the value of the complexity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplexity() {
        return complexity;
    }

    /**
     * Sets the value of the complexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplexity(String value) {
        this.complexity = value;
    }

    /**
     * Gets the value of the lineRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineRate() {
        return lineRate;
    }

    /**
     * Sets the value of the lineRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineRate(String value) {
        this.lineRate = value;
    }

    /**
     * Gets the value of the linesValid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinesValid() {
        return linesValid;
    }

    /**
     * Sets the value of the linesValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinesValid(String value) {
        this.linesValid = value;
    }

    /**
     * Gets the value of the linesCovered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinesCovered() {
        return linesCovered;
    }

    /**
     * Sets the value of the linesCovered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinesCovered(String value) {
        this.linesCovered = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
